"""
Gantt Chart — presentation and detailed PDF rendering.
"""
import io
from datetime import date, datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple

from services.gantt_constants import (
    GANTT_APP_NAME,
    PHASE_CHART_COLORS_HEX,
    PHASE_CHART_STROKES_HEX,
)
from services.gantt_export_service import (
    _format_dependencies,
    _group_tasks_by_phase,
    _parse_iso_date,
    _timeline_bounds,
    _format_month_range,
    _month_tick_dates,
    _week_tick_dates,
)


def build_pdf_bytes(
    project: Dict[str, Any],
    tasks: List[Dict[str, Any]],
    mode: str = "presentation",
) -> bytes:
    if mode == "detailed":
        return _build_detailed_pdf_bytes(project, tasks)
    return _build_presentation_pdf_bytes(project, tasks)


def _build_presentation_pdf_bytes(
    project: Dict[str, Any],
    tasks: List[Dict[str, Any]],
) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A3, landscape
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    PHASE_COLORS = [colors.HexColor(hex_val) for hex_val in PHASE_CHART_COLORS_HEX]
    PHASE_STROKES = [colors.HexColor(hex_val) for hex_val in PHASE_CHART_STROKES_HEX]

    page_size = landscape(A3)
    width, height = page_size
    margin = 12 * mm
    label_col_w = 58 * mm
    footer_h = 8 * mm
    title_block_h = 42 * mm
    continued_header_h = 10 * mm
    chart_header_h = 12 * mm

    phase_groups = _group_tasks_by_phase(tasks)
    dated_tasks = [t for t in tasks if t.get("start_date")]
    min_date, max_date = _timeline_bounds(dated_tasks)
    generated_on = datetime.utcnow().strftime("%d %B %Y")

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=page_size)

    def _truncate(text: str, max_chars: int) -> str:
        text = (text or "").strip()
        return text if len(text) <= max_chars else text[: max_chars - 1] + "..."

    def _draw_footer() -> None:
        pdf.setFont("Helvetica", 7)
        pdf.setFillColor(colors.HexColor("#6b7280"))
        pdf.drawRightString(
            width - margin,
            margin * 0.45,
            f"Generated by {GANTT_APP_NAME}",
        )
        pdf.setFillColor(colors.black)

    def _draw_diamond(cx: float, cy: float, size: float, fill, stroke) -> None:
        half = size / 2
        path = pdf.beginPath()
        path.moveTo(cx, cy + half)
        path.lineTo(cx + half, cy)
        path.lineTo(cx, cy - half)
        path.lineTo(cx - half, cy)
        path.close()
        pdf.setFillColor(fill)
        pdf.setStrokeColor(stroke)
        pdf.drawPath(path, fill=1, stroke=1)
        pdf.setFillColor(colors.black)

    def _draw_title_block() -> float:
        y = height - margin
        pdf.setFont("Helvetica-Bold", 20)
        pdf.drawString(margin, y, project.get("title", "Gantt Export"))
        y -= 9 * mm
        pdf.setFont("Helvetica", 11)
        pdf.setFillColor(colors.HexColor("#374151"))
        pdf.drawString(margin, y, "Project Timeline")
        y -= 6 * mm
        pdf.setFont("Helvetica", 10)
        pdf.drawString(margin, y, _format_month_range(min_date, max_date))
        y -= 5.5 * mm
        pdf.setFont("Helvetica", 9)
        if min_date and max_date:
            pdf.drawString(
                margin,
                y,
                f"Start: {min_date.isoformat()}  |  End: {max_date.isoformat()}  |  "
                f"{len(tasks)} Tasks  |  {len(phase_groups)} Phases",
            )
        else:
            pdf.drawString(
                margin,
                y,
                f"{len(tasks)} Tasks  |  {len(phase_groups)} Phases",
            )
        y -= 4.5 * mm
        pdf.setFont("Helvetica", 8)
        pdf.drawString(margin, y, f"Generated: {generated_on}")
        y -= 4 * mm
        pdf.setStrokeColor(colors.HexColor("#d1d5db"))
        pdf.setLineWidth(0.6)
        pdf.line(margin, y, width - margin, y)
        pdf.setStrokeColor(colors.black)
        pdf.setFillColor(colors.black)
        return y

    def _date_to_x(d: date, chart_left: float, chart_width: float) -> float:
        if not min_date or not max_date:
            return chart_left
        total_days = max((max_date - min_date).days, 1)
        offset = max((d - min_date).days, 0)
        return chart_left + (offset / total_days) * chart_width

    rows: List[Dict[str, Any]] = []
    for phase_idx, (phase_name, phase_tasks) in enumerate(phase_groups):
        rows.append({"kind": "phase", "phase": phase_name, "phase_idx": phase_idx})
        for task in phase_tasks:
            rows.append(
                {"kind": "task", "task": task, "phase_idx": phase_idx, "phase": phase_name}
            )
    if not rows:
        rows.append({"kind": "empty", "phase_idx": 0})

    min_row_h = 3.2 * mm
    max_row_h = 6.5 * mm
    avail_body = height - 2 * margin - title_block_h - footer_h - chart_header_h
    row_h = min(max_row_h, max(min_row_h, avail_body / max(len(rows), 1)))
    rows_per_page = max(int(avail_body // row_h), 1)
    page_chunks = [rows[i : i + rows_per_page] for i in range(0, len(rows), rows_per_page)]

    chart_left = margin + label_col_w
    chart_right = width - margin
    chart_width = chart_right - chart_left
    label_font = max(5.5, min(7.5, 5.5 + (row_h / mm - 3.2) * 0.35))
    phase_font = max(6.5, min(9, 6.5 + (row_h / mm - 3.2) * 0.45))
    header_font = max(6.5, min(8, 6.5 + (row_h / mm - 3.2) * 0.25))

    for page_idx, chunk in enumerate(page_chunks):
        if page_idx > 0:
            pdf.showPage()
        if page_idx == 0:
            chart_top = _draw_title_block() - 4 * mm
        else:
            chart_top = height - margin - continued_header_h
            pdf.setFont("Helvetica-Bold", 10)
            pdf.setFillColor(colors.HexColor("#374151"))
            pdf.drawString(margin, chart_top + 2 * mm, "Project Timeline (continued)")
            pdf.setFillColor(colors.black)

        header_y = chart_top
        if min_date and max_date:
            pdf.setFont("Helvetica-Bold", header_font)
            pdf.setFillColor(colors.HexColor("#4b5563"))
            for tick in _month_tick_dates(min_date, max_date):
                x = _date_to_x(tick, chart_left, chart_width)
                pdf.drawString(x + 1, header_y, tick.strftime("%b %Y"))
            header_y -= chart_header_h * 0.55

            pdf.setStrokeColor(colors.HexColor("#e5e7eb"))
            pdf.setLineWidth(0.35)
            for tick in _week_tick_dates(min_date, max_date):
                x = _date_to_x(tick, chart_left, chart_width)
                pdf.line(x, margin + footer_h, x, chart_top)
            pdf.setStrokeColor(colors.HexColor("#d1d5db"))
            pdf.setLineWidth(0.6)
            for tick in _month_tick_dates(min_date, max_date):
                x = _date_to_x(tick, chart_left, chart_width)
                pdf.line(x, margin + footer_h, x, chart_top)

            today = date.today()
            if min_date <= today <= max_date:
                x = _date_to_x(today, chart_left, chart_width)
                pdf.setStrokeColor(colors.HexColor("#ef4444"))
                pdf.setLineWidth(0.8)
                pdf.line(x, margin + footer_h, x, chart_top)
                pdf.setFont("Helvetica-Bold", 6)
                pdf.setFillColor(colors.HexColor("#ef4444"))
                pdf.drawString(x + 1.5, chart_top + 1, "Today")
                pdf.setFillColor(colors.black)
                pdf.setStrokeColor(colors.black)

        y = header_y - 2 * mm
        for row in chunk:
            bottom = y - row_h
            if row["kind"] == "empty":
                pdf.setFont("Helvetica-Oblique", label_font)
                pdf.drawString(margin, bottom + row_h * 0.32, "No tasks to display")
                y = bottom
                continue

            phase_idx = row.get("phase_idx", 0)
            color = PHASE_COLORS[phase_idx % len(PHASE_COLORS)]
            stroke = PHASE_STROKES[phase_idx % len(PHASE_STROKES)]

            if row["kind"] == "phase":
                pdf.setFillColor(colors.HexColor("#f9fafb"))
                pdf.rect(margin, bottom, width - 2 * margin, row_h, fill=1, stroke=0)
                pdf.setFillColor(color)
                pdf.rect(margin + 2, bottom + row_h * 0.28, 3.5 * mm, 3.5 * mm, fill=1, stroke=0)
                pdf.setFillColor(colors.black)
                pdf.setFont("Helvetica-Bold", phase_font)
                pdf.drawString(
                    margin + 7 * mm,
                    bottom + row_h * 0.28,
                    _truncate(row["phase"].upper(), 48),
                )
                if min_date and max_date:
                    phase_tasks_only = phase_groups[phase_idx][1]
                    phase_dates = [
                        _parse_iso_date(t.get("start_date")) for t in phase_tasks_only
                    ]
                    phase_dates = [d for d in phase_dates if d]
                    if phase_dates:
                        p_start = min(phase_dates)
                        p_ends = [
                            _parse_iso_date(t.get("end_date"))
                            or _parse_iso_date(t.get("start_date"))
                            for t in phase_tasks_only
                        ]
                        p_ends = [d for d in p_ends if d]
                        p_end = max(p_ends) if p_ends else p_start
                        x1 = _date_to_x(p_start, chart_left, chart_width)
                        x2 = _date_to_x(p_end, chart_left, chart_width)
                        pdf.setFillColor(color)
                        pdf.setFillAlpha(0.28)
                        pdf.rect(x1, bottom + row_h * 0.42, max(x2 - x1, 2), 1.2 * mm, fill=1, stroke=0)
                        pdf.setFillAlpha(1)
                y = bottom
                continue

            task = row["task"]
            is_milestone = task.get("type") == "milestone"
            pdf.setFont("Helvetica", label_font)
            prefix = "\u25c6 " if is_milestone else "   "
            pdf.drawString(
                margin + 4 * mm,
                bottom + row_h * 0.3,
                prefix + _truncate(task.get("title") or "", 42),
            )

            start = _parse_iso_date(task.get("start_date"))
            end = _parse_iso_date(task.get("end_date")) or start
            if start and min_date and max_date:
                x_start = _date_to_x(start, chart_left, chart_width)
                if is_milestone:
                    _draw_diamond(x_start, bottom + row_h * 0.45, 3.2 * mm, color, stroke)
                else:
                    x_end = _date_to_x(end or start, chart_left, chart_width)
                    bar_w = max(x_end - x_start, 1.5 * mm)
                    bar_h = min(row_h * 0.42, 3.2 * mm)
                    pdf.setFillColor(color)
                    pdf.setStrokeColor(stroke)
                    pdf.roundRect(
                        x_start,
                        bottom + row_h * 0.24,
                        bar_w,
                        bar_h,
                        1.5,
                        fill=1,
                        stroke=1,
                    )
            pdf.setFillColor(colors.black)
            y = bottom

        _draw_footer()

    pdf.save()
    return buffer.getvalue()


def _build_detailed_pdf_bytes(
    project: Dict[str, Any],
    tasks: List[Dict[str, Any]],
) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    page_size = landscape(A4)
    width, height = page_size
    margin = 15 * mm
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=page_size)

    def draw_header(page_num: int) -> float:
        y = height - margin
        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(margin, y, project.get("title", "Gantt Export"))
        y -= 14
        pdf.setFont("Helvetica", 9)
        pdf.drawString(
            margin,
            y,
            f"Detailed export | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} | {len(tasks)} tasks",
        )
        y -= 10
        pdf.setFont("Helvetica", 8)
        pdf.drawRightString(width - margin, height - margin, f"Page {page_num}")
        return y - 8

    def new_page(page_num: int) -> float:
        if page_num > 1:
            pdf.showPage()
        return draw_header(page_num)

    table_headers = ["#", "Phase", "Title", "Start", "End", "Days", "Status", "Deps"]
    col_widths = [7 * mm, 24 * mm, 58 * mm, 20 * mm, 20 * mm, 12 * mm, 20 * mm, 24 * mm]
    row_height = 5.5 * mm

    page_num = 1
    y = new_page(page_num)
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(margin, y, "Task schedule")
    y -= 10
    pdf.setFont("Helvetica-Bold", 7)
    x = margin
    for header, col_w in zip(table_headers, col_widths):
        pdf.drawString(x + 1 * mm, y, header)
        x += col_w
    y -= row_height
    pdf.setFont("Helvetica", 7)

    for task in tasks:
        if y < margin + row_height:
            page_num += 1
            y = new_page(page_num)
            pdf.setFont("Helvetica-Bold", 7)
            x = margin
            for header, col_w in zip(table_headers, col_widths):
                pdf.drawString(x + 1 * mm, y, header)
                x += col_w
            y -= row_height
            pdf.setFont("Helvetica", 7)

        duration = task.get("duration_days")
        duration_str = "" if duration is None else str(duration)
        deps = _format_dependencies(task.get("dependencies", []))
        cells = [
            str(task.get("order", 0) + 1),
            (task.get("phase") or "")[:16],
            (task.get("title") or "")[:36],
            task.get("start_date") or "",
            task.get("end_date") or "",
            duration_str,
            (task.get("status") or "").replace("_", " "),
            deps[:20],
        ]
        x = margin
        for value, col_w in zip(cells, col_widths):
            pdf.drawString(x + 1 * mm, y, value)
            x += col_w
        y -= row_height

    dated_tasks = [t for t in tasks if t.get("start_date")]
    min_date, max_date = _timeline_bounds(dated_tasks)
    if min_date and max_date and dated_tasks:
        page_num += 1
        y = new_page(page_num)
        pdf.setFont("Helvetica-Bold", 10)
        pdf.drawString(margin, y, "Timeline")
        y -= 12

        chart_left = margin + 55 * mm
        chart_right = width - margin
        chart_width = chart_right - chart_left
        total_days = max((max_date - min_date).days, 1)

        pdf.setFont("Helvetica", 7)
        pdf.drawString(margin, y, min_date.isoformat())
        pdf.drawRightString(chart_right, y, max_date.isoformat())
        y -= 6
        pdf.line(chart_left, y, chart_right, y)
        y -= 4

        bar_height = 4 * mm
        bar_gap = 2 * mm
        for task in dated_tasks:
            if y < margin + bar_height + bar_gap:
                page_num += 1
                y = new_page(page_num)
                pdf.setFont("Helvetica-Bold", 10)
                pdf.drawString(margin, y, "Timeline (continued)")
                y -= 12
                pdf.setFont("Helvetica", 7)

            start = _parse_iso_date(task.get("start_date"))
            end = _parse_iso_date(task.get("end_date")) or start
            if not start:
                continue

            pdf.drawString(margin, y, (task.get("title") or "")[:28])
            start_offset = (start - min_date).days
            end_offset = (end - min_date).days if end else start_offset
            bar_start_x = chart_left + (start_offset / total_days) * chart_width
            bar_end_x = chart_left + (max(end_offset, start_offset) / total_days) * chart_width
            bar_width = max(bar_end_x - bar_start_x, 2)

            if task.get("type") == "milestone":
                pdf.setFillColor(colors.HexColor("#2563eb"))
                pdf.circle(bar_start_x, y + 1.5, 2, fill=1, stroke=0)
            else:
                pdf.setFillColor(colors.HexColor("#3b82f6"))
                pdf.setStrokeColor(colors.HexColor("#1d4ed8"))
                pdf.rect(bar_start_x, y - 1, bar_width, bar_height, fill=1, stroke=1)

            pdf.setFillColor(colors.black)
            y -= bar_height + bar_gap

    pdf.save()
    return buffer.getvalue()
